project:
  type: book

book:
  title: "Quantitative Social Science for Sustainable Futures"
  author:
  - name: Matthew A. Turner
    orcid: 0000-0001-7421-4552
  date: today
  sidebar: 
    logo: images/Cover.png
  # author: "Matthew A. Turner"
  # logo: "images/QSS2SF-word-logo.png"

  repo-url: https://github.com/mt-digital/QSS-Book
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - Programming.qmd
    - Development.qmd
    - Mathematics.qmd
    - BehaviorChange.qmd
    - OpinionChange.qmd
    - Conclusion.qmd
    - References.qmd
  navbar:
    collapse: true
    # pinned: true
    search: true

bibliography: /Users/mt/Workspace/Writing/library.bib

format:
  html:
    toc: true
    toc-title: "Chapter contents"
    html-math-method: katex
    theme: 
      light:
        - theme-light.scss
        # - qss4s-styles.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
        # - qss4s-styles.scss
    fontsize: 1.0em
    linestretch: 1.2
    number-sections: true
    number-depth: 3
